services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn starter.main:app --workers 1 --bind 0.0.0.0:$PORT
    runtime: python
